import '../styles/tailwind.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { MoralisProvider } from 'react-moralis'

function MyApp({ Component, pageProps }: AppProps) {
  return (
  <>
    <Head>
      <title>Social Impact</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <MoralisProvider
      appId="oXxFHo2Yz29rUfncfneSRh7fOKzuV3FzmUjdNdWe"
      serverUrl="https://lbpsvvhshu0i.usemoralis.com:2053/server"
    >
      <Component {...pageProps} />
    </MoralisProvider>
  </>
  )
}

export default MyApp
