import "../styles/tailwind.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import { MoralisProvider } from "react-moralis";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Social Impact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MoralisProvider
        appId={process.env.NEXT_PUBLIC_MORALIS_APP_ID!}
        serverUrl={process.env.NEXT_PUBLIC_MORALIS_SERVER_URL!}
      >
        <Component {...pageProps} />
      </MoralisProvider>
    </>
  );
}

export default MyApp;
