import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../src/components/About/About'
import Footer from '../src/components/Footer/Footer'
import Hero from '../src/components/Hero/Hero'
import { Navbar } from '../src/components/Navbar/Navbar'
import Steps from '../src/components/Steps/Steps'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Social Impact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
      <main>
        <Hero />
        <About />
        <Steps />
        <Footer />
      </main>
    </div>
  )
}

export default Home
